"""
Topology Correction Module

Provides the correction workflow for iterative topology refinement:
  - CorrectionSession: state tracker for iterative correction cycles
  - apply_soft_correction: re-proposes with user feedback injected into clarifications
  - export_draft: writes annotated proposal-draft.json for hard correction editing
  - import_draft: loads proposal-draft.json, strips comment annotations, lints

Soft correction = LLM re-proposal with feedback injected.
Hard correction = User manually edits proposal-draft.json; import validates it.

Requirements: CORR-01 (CorrectionSession), CORR-02 (soft correction),
              CORR-03 (cycle limit), CORR-05 (export/import draft).
"""

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, List, Optional

from openclaw.topology.linter import ConstraintLinter, LintResult
from openclaw.topology.models import EdgeType, TopologyGraph
from openclaw.topology.proposal_models import ProposalSet, RubricScore, TopologyProposal
from openclaw.topology.proposer import build_proposals, generate_proposals_sync
from openclaw.topology.rubric import score_proposal
from openclaw.topology.storage import _topology_dir

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# CorrectionSession dataclass
# ---------------------------------------------------------------------------

@dataclass
class CorrectionSession:
    """
    Tracks the state of an iterative correction workflow.

    Holds cycle count, max cycles, the current and best proposal sets,
    the original outcome/project context, and a correction history.

    Fields:
        outcome: The original task outcome description.
        project_id: The project identifier.
        proposal_set: The current (most recent) ProposalSet from the LLM.
        best_proposal_set: The highest-confidence ProposalSet seen so far.
        registry: AgentRegistry for linting and re-proposal.
        max_concurrent: Max concurrent L3 agents (pool constraint).
        cycle_count: Number of correction cycles completed so far (default 0).
        max_cycles: Maximum allowed correction cycles before hard lock (default 3).
        approved_proposal: The proposal the user ultimately approved (optional).
        correction_history: Log of all correction events (type, feedback, cycle).
        clarifications: Existing clarification context (merged with new feedback).
    """

    outcome: str
    project_id: str
    proposal_set: ProposalSet
    best_proposal_set: ProposalSet
    registry: Any  # AgentRegistry — typed as Any to avoid circular import
    max_concurrent: int = 3
    cycle_count: int = 0
    max_cycles: int = 3
    approved_proposal: Optional[TopologyProposal] = None
    correction_history: List[dict] = field(default_factory=list)
    clarifications: dict = field(default_factory=dict)

    @property
    def cycle_limit_reached(self) -> bool:
        """True when cycle_count has reached or exceeded max_cycles."""
        return self.cycle_count >= self.max_cycles


# ---------------------------------------------------------------------------
# apply_soft_correction
# ---------------------------------------------------------------------------

def apply_soft_correction(
    session: CorrectionSession,
    feedback: str,
    weights: dict,
) -> ProposalSet:
    """
    Apply a soft correction by re-proposing with user feedback injected.

    Checks cycle limit first — raises ValueError if exceeded.
    Increments cycle_count, calls generate_proposals_sync with feedback
    injected into clarifications["user_feedback"], builds and scores
    proposals, updates session.proposal_set and session.best_proposal_set
    if the new top proposal has higher overall_confidence.

    Args:
        session: The active CorrectionSession to update in place.
        feedback: User's natural-language feedback for this correction cycle.
        weights: Rubric scoring weights (dict of dimension -> float).

    Returns:
        The new ProposalSet generated by the LLM.

    Raises:
        ValueError: If session.cycle_limit_reached is True before calling LLM.
    """
    if session.cycle_limit_reached:
        raise ValueError(
            f"Cycle limit reached ({session.cycle_count}/{session.max_cycles}). "
            "Use export_draft/import_draft for hard correction or accept the best proposal."
        )

    # Increment cycle before LLM call (cycle N starts at increment)
    session.cycle_count += 1

    # Build augmented clarifications with user feedback
    augmented_clarifications = {**session.clarifications, "user_feedback": feedback}

    # Call LLM for new proposals
    logger.debug(
        "Soft correction cycle %d for project=%s (feedback=%r)",
        session.cycle_count,
        session.project_id,
        feedback[:80],
    )
    raw = generate_proposals_sync(
        outcome=session.outcome,
        project_id=session.project_id,
        registry=session.registry,
        max_concurrent=session.max_concurrent,
        clarifications=augmented_clarifications,
    )

    # Build TopologyProposal objects (unified class with .graph field)
    proposer_proposals = build_proposals(raw, session.project_id)

    # Lint each proposal with ConstraintLinter
    linter = ConstraintLinter(registry=session.registry, max_concurrent=session.max_concurrent)
    pm_proposals = []
    assumptions_from_raw = []

    for arch_key in ("lean", "balanced", "robust"):
        arch_data = raw.get(arch_key, {})
        if not assumptions_from_raw and arch_data.get("assumptions"):
            assumptions_from_raw = arch_data.get("assumptions", [])

    for prop in proposer_proposals:
        # Build linter-compatible proposal dict
        lint_proposal_dict = {
            "roles": [
                {
                    "id": n.id,
                    "level": n.level,
                    "intent": n.intent,
                    "risk_level": n.risk_level,
                }
                for n in prop.graph.nodes
            ],
            "edges": [
                {
                    "from": e.from_role,
                    "to": e.to_role,
                    "type": e.edge_type.value,
                }
                for e in prop.graph.edges
            ],
        }
        lint_result = linter.lint(prop.archetype, lint_proposal_dict)

        # Score the proposal
        rubric = score_proposal(prop.graph, weights)

        # Attach score to the unified TopologyProposal
        prop.rubric_score = rubric
        pm_proposals.append(prop)

    # Build new ProposalSet
    new_set = ProposalSet(
        proposals=pm_proposals,
        assumptions=assumptions_from_raw,
        outcome=session.outcome,
    )

    # Update session.proposal_set
    session.proposal_set = new_set

    # Update best_proposal_set if new top proposal has higher overall_confidence
    new_top_confidence = _top_confidence(new_set)
    best_confidence = _top_confidence(session.best_proposal_set)

    if new_top_confidence > best_confidence:
        session.best_proposal_set = new_set
        logger.debug(
            "Updated best_proposal_set: new confidence %d > old %d",
            new_top_confidence,
            best_confidence,
        )

    # Record correction in history
    session.correction_history.append({
        "type": "soft",
        "feedback": feedback,
        "cycle": session.cycle_count,
    })

    return new_set


def _top_confidence(proposal_set: ProposalSet) -> int:
    """Return the highest overall_confidence in a ProposalSet, or 0 if none."""
    best = 0
    for p in proposal_set.proposals:
        if p.rubric_score and p.rubric_score.overall_confidence > best:
            best = p.rubric_score.overall_confidence
    return best


# ---------------------------------------------------------------------------
# export_draft
# ---------------------------------------------------------------------------

def export_draft(proposal: TopologyProposal, project_id: str) -> Path:
    """
    Export a proposal's topology to proposal-draft.json for hard correction.

    Writes the topology graph dict with human-readable __comment__ annotations
    to help users understand what to edit. The comment keys are stripped on
    import_draft().

    Args:
        proposal: The TopologyProposal to export.
        project_id: The project identifier (determines output directory).

    Returns:
        Path to the written proposal-draft.json file.
    """
    topo_dir = _topology_dir(project_id)
    draft_path = topo_dir / "proposal-draft.json"

    # Build the topology dict
    data = proposal.graph.to_dict()

    # Add human-readable comment annotations
    data["__comment__nodes"] = (
        "Nodes: each has id (string), level (1/2/3), intent (what role does), "
        "risk_level (low/medium/high)"
    )
    data["__comment__edges"] = (
        "Edges: from_role/to_role (node ids), edge_type: "
        "delegation | coordination | review_gate | escalation | information_flow"
    )

    with open(draft_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

    logger.debug("Exported draft topology to %s", draft_path)
    return draft_path


# ---------------------------------------------------------------------------
# import_draft
# ---------------------------------------------------------------------------

def import_draft(
    project_id: str,
    registry: Any,
    max_concurrent: int,
) -> tuple:
    """
    Import and validate a manually-edited proposal-draft.json.

    Strips __comment__ keys, deserializes to TopologyGraph, and runs the
    constraint linter. Raises a clear ValueError on invalid edge_type values
    listing all valid options.

    Args:
        project_id: The project identifier (determines file location).
        registry: AgentRegistry for constraint linting.
        max_concurrent: Max concurrent L3 agents for pool constraint check.

    Returns:
        (TopologyGraph, LintResult) tuple.

    Raises:
        FileNotFoundError: If proposal-draft.json does not exist.
        ValueError: If edge_type values are invalid, with valid types listed.
    """
    topo_dir = _topology_dir(project_id)
    draft_path = topo_dir / "proposal-draft.json"

    if not draft_path.exists():
        raise FileNotFoundError(
            f"No proposal-draft.json found at {draft_path}. "
            "Run 'export_draft' first to create the draft file."
        )

    with open(draft_path, "r", encoding="utf-8") as f:
        raw = json.load(f)

    # Strip __comment__ keys
    clean = {k: v for k, v in raw.items() if not k.startswith("__comment__")}

    # Deserialize to TopologyGraph — catch invalid edge_type values with clear error
    valid_edge_types = [e.value for e in EdgeType]
    try:
        graph = TopologyGraph.from_dict(clean)
    except ValueError as exc:
        raise ValueError(
            f"Invalid edge_type in proposal-draft.json: {exc}. "
            f"Valid EdgeType values are: {', '.join(valid_edge_types)}"
        ) from exc

    # Build linter-compatible proposal dict
    lint_proposal_dict = {
        "roles": [
            {
                "id": n.id,
                "level": n.level,
                "intent": n.intent,
                "risk_level": n.risk_level,
            }
            for n in graph.nodes
        ],
        "edges": [
            {
                "from": e.from_role,
                "to": e.to_role,
                "type": e.edge_type.value,
            }
            for e in graph.edges
        ],
    }

    # Run constraint linter
    linter = ConstraintLinter(registry=registry, max_concurrent=max_concurrent)
    lint_result = linter.lint("hard_correction", lint_proposal_dict)

    logger.debug(
        "Imported draft topology for project=%s (valid=%s, adjusted=%s)",
        project_id,
        lint_result.valid,
        lint_result.adjusted,
    )

    return graph, lint_result
