"""
Topology Proposal Data Models

Defines the data structures for topology proposals generated by the Structure
Proposal Engine. These models capture LLM output and carry it through scoring
(rubric), validation (linter), and user presentation layers.

Design: Uses @dataclass (consistent with TopologyGraph and AgentSpec patterns).
"""

from dataclasses import dataclass, field
from typing import List, Optional

from .models import TopologyGraph


@dataclass
class RubricScore:
    """
    Quantitative scoring of a topology proposal across 7 dimensions.

    All dimension scores are integers in the range [0, 10].
    Higher is always better across all dimensions (scores are normalized so
    that high complexity score means "this topology is not complex").

    Fields:
        complexity:             Low node/edge count = high score. Simple is good.
        coordination_overhead:  Fewer coordination edges = high score.
        risk_containment:       More review gates and escalation = high score.
        time_to_first_output:   Shorter chain depth = high score.
        cost_estimate:          Fewer roles = high score (proxy for resource cost).
        preference_fit:         Always 5 pre-Phase 64 (neutral baseline).
        overall_confidence:     Weighted average of above 6 dimensions, 0-10.
        key_differentiators:    Dimension names where proposals differ most (>= 3 spread).
    """

    complexity: int
    coordination_overhead: int
    risk_containment: int
    time_to_first_output: int
    cost_estimate: int
    preference_fit: int
    overall_confidence: int
    key_differentiators: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "complexity": self.complexity,
            "coordination_overhead": self.coordination_overhead,
            "risk_containment": self.risk_containment,
            "time_to_first_output": self.time_to_first_output,
            "cost_estimate": self.cost_estimate,
            "preference_fit": self.preference_fit,
            "overall_confidence": self.overall_confidence,
            "key_differentiators": self.key_differentiators,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "RubricScore":
        return cls(
            complexity=data["complexity"],
            coordination_overhead=data["coordination_overhead"],
            risk_containment=data["risk_containment"],
            time_to_first_output=data["time_to_first_output"],
            cost_estimate=data["cost_estimate"],
            preference_fit=data["preference_fit"],
            overall_confidence=data["overall_confidence"],
            key_differentiators=data.get("key_differentiators", []),
        )


@dataclass
class TopologyProposal:
    """
    A single topology proposal representing one archetype option.

    Carries all information needed for the user to evaluate the proposal:
    structural graph, delegation boundaries, coordination model, risk
    assessment, justification, assumptions, and optional rubric score.

    archetype: "lean", "balanced", or "robust"
    graph: The full TopologyGraph representing this option
    delegation_boundaries: Human-readable description of role boundaries
    coordination_model: How agents coordinate (e.g. "direct", "via-pm")
    risk_assessment: Qualitative risk description
    justification: Why this topology fits the task
    assumptions: Shared assumptions applied when generating this proposal
    rubric_score: Optional quantitative scoring (set by RubricScorer)
    """

    archetype: str
    graph: TopologyGraph
    delegation_boundaries: str
    coordination_model: str
    risk_assessment: str
    justification: str
    assumptions: List[str] = field(default_factory=list)
    rubric_score: Optional[RubricScore] = None

    def to_dict(self) -> dict:
        return {
            "archetype": self.archetype,
            "graph": self.graph.to_dict(),
            "delegation_boundaries": self.delegation_boundaries,
            "coordination_model": self.coordination_model,
            "risk_assessment": self.risk_assessment,
            "justification": self.justification,
            "assumptions": self.assumptions,
            "rubric_score": self.rubric_score.to_dict() if self.rubric_score else None,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "TopologyProposal":
        rubric_data = data.get("rubric_score")
        # Accept both "graph" (new) and "topology" (legacy) keys for backward compat
        graph_data = data.get("graph") or data.get("topology")
        return cls(
            archetype=data["archetype"],
            graph=TopologyGraph.from_dict(graph_data),
            delegation_boundaries=data["delegation_boundaries"],
            coordination_model=data["coordination_model"],
            risk_assessment=data["risk_assessment"],
            justification=data["justification"],
            assumptions=data.get("assumptions", []),
            rubric_score=RubricScore.from_dict(rubric_data) if rubric_data else None,
        )


@dataclass
class ProposalSet:
    """
    A set of topology proposals generated for a single task.

    Contains all 3 archetype proposals (lean, balanced, robust), shared
    assumptions about the task, and the intended outcome.

    proposals:   List of TopologyProposal (typically 3: lean/balanced/robust)
    assumptions: Shared assumptions made while generating proposals
    outcome:     The task/goal these proposals address
    """

    proposals: List[TopologyProposal]
    assumptions: List[str]
    outcome: str

    def to_dict(self) -> dict:
        return {
            "proposals": [p.to_dict() for p in self.proposals],
            "assumptions": self.assumptions,
            "outcome": self.outcome,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ProposalSet":
        return cls(
            proposals=[TopologyProposal.from_dict(p) for p in data.get("proposals", [])],
            assumptions=data.get("assumptions", []),
            outcome=data["outcome"],
        )
