import { NextRequest, NextResponse } from 'next/server';
import { getDb } from '@/lib/db';
import { withAuth } from '@/lib/auth-middleware';
import { withWriteLock } from '@/lib/safety';
import path from 'path';
import fs from 'fs/promises';
import os from 'os';
import crypto from 'crypto';
import { z } from 'zod';

const OPENCLAW_ROOT = process.env.OPENCLAW_ROOT || path.join(os.homedir(), '.openclaw');
const AGENTS_DIR = path.join(OPENCLAW_ROOT, 'agents');

const AgentCreateSchema = z.object({
    id: z.string().regex(/^[a-z0-9-_]+$/),
    name: z.string().min(1),
    model: z.object({
        id: z.string(),
        provider: z.string()
    }).optional(),
    level: z.number().default(1),
    sandbox: z.string().default('non-main')
});

async function handler(request: NextRequest): Promise<NextResponse> {
    const requestId = crypto.randomUUID();
    try {
        const body = await request.json();
        const validated = AgentCreateSchema.parse(body);
        const agentDir = path.join(AGENTS_DIR, validated.id);

        // 1. Safety checks
        try {
            await fs.access(agentDir);
            return NextResponse.json({ error: 'Agent already exists' }, { status: 409 });
        } catch {
            // Good, doesn't exist
        }

        // 2. Create directory structure
        await fs.mkdir(agentDir, { recursive: true });

        // 3. Create manifest (agent.json)
        const manifest = {
            id: validated.id,
            name: validated.name,
            level: validated.level,
            model: validated.model,
            sandbox: { mode: validated.sandbox },
            created_at: new Date().toISOString()
        };
        await fs.writeFile(path.join(agentDir, 'agent.json'), JSON.stringify(manifest, null, 2));

        // 4. Create python scaffolds
        const agentPy = `# Agent: ${validated.name}\n\nasync function main():\n    pass\n`;
        await fs.writeFile(path.join(agentDir, 'agent.py'), agentPy);
        await fs.writeFile(path.join(agentDir, 'tools.py'), '# Register tools here\n');
        await fs.writeFile(path.join(agentDir, 'README.md'), `# ${validated.name}\n\nGenerated by OpenClaw Dashboard Agent Builder.\n`);

        // 5. Index in database
        const db = getDb();
        db.prepare(`
      INSERT INTO agents (id, name, path, level, model_id, provider_id, enabled, last_indexed, metadata_json)
      VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?)
    `).run(
            validated.id,
            validated.name,
            path.relative(OPENCLAW_ROOT, agentDir),
            validated.level,
            validated.model?.id || null,
            validated.model?.provider || null,
            1,
            JSON.stringify(manifest)
        );

        // 6. Audit log
        db.prepare(`
      INSERT INTO audit_log (id, request_id, actor, action, target, after_json, diff_summary, status)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
            crypto.randomUUID(),
            requestId,
            'user',
            'agent_create',
            `agent:${validated.id}`,
            JSON.stringify(manifest),
            `Created agent: ${validated.name} (${validated.id})`,
            'success'
        );

        return NextResponse.json({
            success: true,
            requestId,
            agentId: validated.id,
            path: path.relative(OPENCLAW_ROOT, agentDir)
        });
    } catch (error: any) {
        if (error instanceof z.ZodError) {
            return NextResponse.json({ error: 'Invalid agent data', details: error.errors }, { status: 400 });
        }
        console.error('Error creating agent:', error);
        return NextResponse.json({ error: 'Failed to create agent', message: error.message }, { status: 500 });
    }
}

export const POST = withAuth(withWriteLock(handler));
